-- Создание таблиц в БД

CREATE TABLE IF NOT EXISTS organizations (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    inn VARCHAR UNIQUE NOT NULL,
    account VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS bills (
    id SERIAL NOT NULL PRIMARY KEY,
    number VARCHAR UNIQUE NOT NULL,
    date DATE NOT NULL,
    sender_id INTEGER REFERENCES organizations (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS merch (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    code VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS bill_items (
    id SERIAL NOT NULL PRIMARY KEY,
    price FLOAT NOT NULL check ( price > 0 ),
    bill_id INTEGER NOT NULL REFERENCES bills (id) ON DELETE CASCADE ON UPDATE CASCADE,
    merch_id INTEGER NOT NULL REFERENCES merch (id) ON DELETE RESTRICT ,
    quantity INTEGER NOT NULL CHECK ( quantity > 0 )
)

